### ISSUE TITLE
Twilight Forest

### ISSUE THREAD

**Issue by Datraen** [cocoacraft/cocoacraft#9] opened 2014-06-16 18:11 UTC
With the removal of Mystcraft and Dimensional Doors, I am asking again to have Twilight Forest added to the mod list.
http://www.minecraftforum.net/topic/561673-172-the-twilight-forest-v211-new-progression-system/
https://dl.dropboxusercontent.com/u/38679977/twilightforest-1.6.4-1.20.5.jar

**Comment by Karunamon** [comment] 2014-06-19 17:10
Haven't fogotten you, but this is a dupe of #3 :)

**Closed as completed by Karunamon** 2014-06-19 17:10 UTC
